import StyledComponentsRegistry from "@/utils/Registery";
import "./globals.css";
// import "./globals.scss";
import { Inter } from "next/font/google";
import { HeaderComponent } from "@/components/Header";
import { PageLayout } from "@/components/PageLayout/";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Travel Itineray",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <PageLayout>{children}</PageLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
